### ISSUE TITLE
LLC client auth options should be specified in the readme.md rather than client autorest.md files

### ISSUE THREAD

**Issue by christothes** [Azure/autorest.csharp#1208]
For LLC generation, the generating client code must specify something like:

```yaml
credential-types: TokenCredential
credential-scopes: "https://confidential-ledger.azure.com/.default"
low-level-client: true
```

Everything but the `low-level-client: true` line should be defined by the service in its readme.md rather than by the generating client code's autorest.md.

There should be a way to define these properties so that they only apply to when `low-level-client: true`  is specified.
