### ISSUE TITLE
Autorest 'public-clients : true' doesn't generate public clients 

### ISSUE THREAD

**Issue by swashtek** [Azure/autorest.csharp#1210]
Autorest (3.2.1) with 'public-clients: true' flag doesn't generate public clients. We don't see constructor which takes parameters for http client or base uri. Also, there is another constructor with ClientDiagnostics and HttpPipeline which is internal, so not accessible. 
How do we get around this ? Are there any steps to perform to make it accessible ? 
Please direct us to examples if any. Thank you. 

``` yaml
clear-output-folder: true
input-file: swagger.json
output-folder: Generated 
csharp: true
namespace: SampleNamespace
override-client-name: SampleClient
v3: true
verbose: true
skip-csproj: true
public-clients : true
```
