### ISSUE TITLE
Bug: BuildObject with Multipart from v3

### ISSUE THREAD

**Issue by janek9971** [Azure/autorest.csharp#1283]
I encountered an internal error in autorest for method in api called UploadPicture. Nswag did not have any problem with this.

I attach zipped  Configuration.json and CodeModel.yaml
[Configuration.zip](https://github.com/Azure/autorest.csharp/files/6575683/Configuration.zip)

Error message:

> Exception: BuildObject with Multipart from UploadPicture
   at AutoRest.CSharp.Output.Builders.SerializationBuilder.BuildObject(KnownMediaType mediaType, ObjectSchema objectSchema, SchemaObjectType type) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Builders\SerializationBuilder.cs:line 28
   at AutoRest.CSharp.Output.Models.Types.SchemaObjectType.<BuildSerializations>b__45_0(KnownMediaType type) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\SchemaObjectType.cs:line 333
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoRest.CSharp.Output.Models.Types.SchemaObjectType.BuildSerializations() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\SchemaObjectType.cs:line 328
   at AutoRest.CSharp.Output.Models.Types.SchemaObjectType.get_Serializations() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\SchemaObjectType.cs:line 66
   at AutoRest.CSharp.Generation.Writers.SerializationWriter.WriteObjectSerialization(CodeWriter writer, SchemaObjectType model) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\SerializationWriter.cs:line 34
   at AutoRest.CSharp.Generation.Writers.SerializationWriter.WriteSerialization(CodeWriter writer, TypeProvider schema) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\SerializationWriter.cs:line 30
   at AutoRest.CSharp.AutoRest.Plugins.DataPlaneTarget.Execute(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\DataPlane\AutoRest\DataPlaneTarget.cs:line 34
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 56
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 96

**Comment by AlexGhiondea** [comment]
@AlexanderSher could you take a look?

**Comment by AlexanderSher** [comment]
Minimal input to repro the issue:
```
openapi: "3.0.0"
info:
  title: Multipart
  version: 1.0.0
servers:
  - url: http://test.swagger.io/v1
paths:
  /pets:
    post:
      operationId: testOp
      responses:
        '201':
          description: Null response
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                test:
                  type: object
                  properties:
                    test:
                      type: integer
                fileName:
                  type: string
                  format: binary
```

**Comment by AlexanderSher** [comment]
This is an object schema that has `serializationFormats` that isn't supported.
```
  objects:
    - !ObjectSchema &ref_2
      type: object
      apiVersions:
        - !ApiVersion 
          version: 1.0.0
      properties:
        - !Property 
          schema: *ref_1
          serializedName: nested
          language: !Languages 
            default:
              name: nested
              description: ''
          protocol: !Protocols {}
      serializationFormats:
        - multipart
      usage:
        - input
      extensions:
        x-internal-autorest-anonymous-schema:
          anonymous: true
      language: !Languages 
        default:
          name: PostContentSchemaTest
          description: ''
          namespace: ''
      protocol: !Protocols {}
```
