### ISSUE TITLE
Customization does not work

### ISSUE THREAD

**Issue by trojanmartin** [Azure/autorest.csharp#1370]
What am i doing wrong, when code customization does not work? 

 readme.md
``` yaml
require: $(this-folder)/../readme.md
input-file: $(this-folder)/../../swagger/TaxManagementAPI/swagger.yaml
output-folder: ./Generated
csharp: true
namespace: TaxManagement.RestClient
```
MessageBaseTest.cs

``` 
using Azure.Core;
namespace TaxManagement.RestClient.Models
{
    [CodeGenModel("MessageBase")]
    public partial class MessageBaseTest { }
}
```
Then i run 

`autorest --use:@autorest/csharp@3.0.0-beta.20210210.4  .\readme.md `

and nothing has changed in Generated/MessageBase.cs.
I also tried it in sample repo. However, the result was the same.
https://github.com/Azure/autorest.csharp/tree/feature/v3/samples/Azure.Storage.Tables
