### ISSUE TITLE
TokenCredentials when azure-arm is false

### ISSUE THREAD

**Issue by estoel81** [Azure/autorest.csharp#1390]
**Describe the issue or request**
I want to generate a client which can use a TokenCredential, but when I try to generate a client it will give the following error:

```
FATAL: Malformed 'operationId' detected. Check swagger definition and make sure every 'operationId' follows form of 'Noun_Verb'. For details, refer to: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r1001
```

I don't want to change all the operationId's. Is there a way to disable these kinds of validations when the Azure-ARM flag is enabled?

**Describe your ideas for solutions**
--

**Settings**
``` yaml $(tag) == 'local'
input-file:         http://localhost:5000/swagger/v1/swagger.json
output-folder:      ./GeneratedClient
namespace:          ApiTests.Client.GeneratedClient
csharp:             true
generate-metadata:  true
azure-arm:          true
add-credential:     true
azure-validator:    false
client-side-validation: false
public-clients:     true
```
