### ISSUE TITLE
Feature request: support uri format type for string.

### ISSUE THREAD

**Issue by guperrot** [Azure/autorest.csharp#141]
When adding `format: uri` (standard swagger format) to a string property in a definition, the generated c# object still uses string.
Format: uuid works fine and generates Guid type, but for uri it keeps string type.

```
autorest --info
AutoRest code generation utility [version: 2.0.4245; node: v8.10.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4245     C:\Users\guperrot\AppData\Local\Temp\.autorest\@microsoft.azure_autorest-core@2.0.4245
 extension  @microsoft.azure/autorest.csharp         2.2.57       C:\Users\guperrot\AppData\Local\Temp\.autorest\@microsoft.azure_autorest.csharp@2.2.57
 extension  @microsoft.azure/autorest.modeler        2.3.43       C:\Users\guperrot\AppData\Local\Temp\.autorest\@microsoft.azure_autorest.modeler@2.3.43
 extension  @microsoft.azure/autorest.modeler        2.3.44       C:\Users\guperrot\AppData\Local\Temp\.autorest\@microsoft.azure_autorest.modeler@2.3.44
 extension  @microsoft.azure/autorest.nodejs         2.1.32       C:\Users\guperrot\AppData\Local\Temp\.autorest\@microsoft.azure_autorest.nodejs@2.1.32
```

Definition:

```
  DataSubjectRightQueueInfo:
    type: object
    properties:
      sasUri:
        type: string
        format: uri
      queueName:
        type: string
      expiresAt:
        type: string
        format: date-time
    required:
      - sasUri
      - queueName
      - expiresAt
```

Generated code:

```
        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sasUri")]
        public string SasUri { get; set; }
```

Expected: `public Uri SasUri`
