### ISSUE TITLE
Lists of enum's generating as nullable elements in C# clients (ie List<SomeEnum?>)

### ISSUE THREAD

**Issue by geoffreys** [Azure/autorest.csharp#145]
When outputting C#, autorest is generating Lists of nullable enum's eg List<SomeEnum?> instead of the expected List<SomeEnum>.

This issue occurs even when x-nullable: false and x-ms-enum are included in the metadata.  The behavior is illogical, especially when tagged with x-nullable: false.  The x-nullable element can't be included in the items[] array.

Example Swagger snippet:
```
{
   "SomeEnumList":{
      "type":"array",
      "items":{
         "enum":[
            "Unknown",
            "Cat",
            "Dog",
            "Cow"
         ],
         "type":"string",
         "x-ms-enum":{
            "name":"SomeEnum",
            "modelAsString":false
         }
      },
      "x-nullable":false
   }
}
```

**Autorest version**
Version: 2.0.4262
Node: v8.6.0

**Comment by markm77** [comment]
I also noticed the following Swagger
```yaml
      grant_types:
        type: array
        items:
          type: string
          enum:
            - client_credentials
            - authorization_code
            - refresh_token
          x-ms-enum:
            name: grant_types_item_enum
            modelAsString: false
        minItems: 1
```

leads to an IList with nullable elements (```IList<GrantTypesItemEnum?>``` rather than ```IList<GrantTypesItemEnum>``` as expected):
```csharp
        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grant_types")]
        public IList<GrantTypesItemEnum?> GrantTypes { get; set; }
```

It's not clear the validation checks for min items of 1 either.

Mentioning these points so hopefully can be fixed in new generator.
