### ISSUE TITLE
Constructor parameters in wrong order after setting default value with transform

### ISSUE THREAD

**Issue by kinelski** [Azure/autorest.csharp#2015]
I'm trying to use a transform to set a default value to a property in the Form Recognizer swagger ([link here](https://github.com/Azure/azure-rest-api-specs-pr/blob/3080959fbda0b602e0af875d4b90a094c0f6016e/specification/cognitiveservices/data-plane/FormRecognizer/preview/2022-01-30-preview/FormRecognizer.json#L1514-L1520)). Here's the property:
```json
"rowSpan": {
  "description": "Number of rows spanned by this cell.",
  "type": "integer",
  "format": "int32",
  "minimum": 1,
  "default": 1
}
```

And here's the transform. Note that I'm redefining the `required` property to include `rowSpan`:
```yaml
directive:
  from: swagger-document
  where: $.definitions.DocumentTableCell
  transform: >
    $.required = ["rowIndex", "columnIndex", "content", "spans", "rowSpan"];
    $.properties.rowSpan["x-ms-client-default"] = 1;
```

The generated code sets the default as specified, but it doesn't place the optional `rowSpan` parameter at the end of the constructor signature, making the build fail:
```cs
public partial class DocumentTableCell
{
    // Places rowSpan (optional) before required parameters, so build fails.
    internal DocumentTableCell(int rowIndex, int columnIndex, int rowSpan = 1, string content, IEnumerable<DocumentSpan> spans)
    {
        ...
    }
}
```
