### ISSUE TITLE
Auth AADToken and AzureKey do not support at the same time

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2217]
According to quick start doc
https://github.com/Azure/azure-sdk-for-net/blob/3b2801f96f4f43eccb36f78f3fe4d993af570875/doc/DataPlaneCodeGeneration/AzureSDKCodeGeneration_DataPlane_Quickstart.md#L209, we should support both AADToken and AzureKey as 
```yaml
security: AADToken;AzureKey
security-header-name: Your-Subscription-Key
security-scopes: https://yourendpoint.azure.com/.default
```
Repro steps:
1. Add above configuration to any service autorest.md (e.g., sdk\metricsadvisor\Azure.AI.MetricsAdvisor\src\autorest.md)
2. Run `dotnet build /t:GenerateCode` to generate code.

Actual result:

> EXEC : fatal   | error : Unexpected security scheme 'AADToken;AzureKey'. Only known schemes are AADToken,AzureKey,Anonymous [D:\GIT\azure-sdk-for-net\sdk\metricsadvisor\Azure.AI.MetricsAdvisor\src\Azure.AI.MetricsAdvisor.csproj]
>   fatal   | Process() cancelled due to failure
> EXEC : error   | error : Plugin modelerfour reported failure. [D:\GIT\azure-sdk-for-net\sdk\metricsadvisor\Azure.AI.MetricsAdvisor\src\Azure.AI.MetricsAdvisor.csproj]

Notice: below two could generate successfully:
```yaml
security: AADToken
security-scopes: https://cognitiveservices.azure.com/.default
```
```yaml
security: AzureKey
security-header-name: Your-Subscription-Key
```
