### ISSUE TITLE
Support `externalDocs.url` from swagger

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#2384]
In addition to - or even in lieu of - #2376, it would be great to see the data plane generator support `externalDocs.url` like the LLC generator does:

* Optional remarks: https://cs.github.com/Azure/autorest.csharp/blob/48a4048042f0a5e06a48b8b4ef2641035a3fdc4e/src/AutoRest.CSharp/LowLevel/Generation/LowLevelClientWriter.cs#L594
* Calls https://cs.github.com/Azure/autorest.csharp/blob/48a4048042f0a5e06a48b8b4ef2641035a3fdc4e/src/AutoRest.CSharp/LowLevel/Generation/LowLevelClientWriter.cs#L597 which gets the `externalDocs.url` from autorest, which comes from the same elements from the swagger schema.

For reference, I tried to add this via transforms but it doesn't work. Only the line to override the description works, but Visual Studio does not make links clickable by default without using `<see href="{url}/>`. I can't use that here, though, because XML entities are encoded when writing to the `CodeWriter`.

```yaml
# Update descriptions to include a link to the REST API documentation.
- from: analyzeconversations.json
  where: $.paths.*.*
  transform: |
    var operationId = $.operationId.substring("ConversationAnalysis_".length);
    $["externalDocs"] = {
        url: "https://docs.microsoft.com/rest/api/language/conversation-analysis-runtime/" + operationId.replace(/([a-z0–9])([A-Z])/g, "$1-$2").toLowerCase()
    };
    $.description = $.description + " See https://docs.microsoft.com/rest/api/language/conversation-analysis-runtime/" + operationId.replace(/([a-z0–9])([A-Z])/g, "$1-$2").toLowerCase() + " for more information.";

- from: analyzeconversations-authoring.json
  where: $.paths.*.*
  transform: |
    var operationId = $.operationId.substring("ConversationalAnalysisAuthoring_".length);
    $["externalDocs"] = {
        url: "https://docs.microsoft.com/rest/api/language/conversational-analysis-authoring/" + operationId.replace(/([a-z0–9])([A-Z])/g, "$1-$2").toLowerCase()
    };
    $.description = $.description + " See https://docs.microsoft.com/rest/api/language/conversational-analysis-authoring/" + operationId.replace(/([a-z0–9])([A-Z])/g, "$1-$2").toLowerCase() + " for more information.";
```
