### ISSUE TITLE
[TestGen] Test Generator cannot catch the code replacement from customized code

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#2394]
In some cases we might have some customized code to replace some elements in the auto-generated source code, our test generator should have the ability to catch those changes and use correct symbols in the generated test cases. For instance:
https://github.com/Azure/azure-sdk-for-net/blob/87244af8bc606f41d73a34b03f0797103a600d96/sdk/workloads/Azure.ResourceManager.Workloads/src/Customization/Models/WordPressVersion.cs#L20
Here we are using some customized code to replace the things inside the auto-generated source code.
The root cause of this might be that the test generator is not loading the same `SourceInputModel` as we did in the source code generation.

**Comment by ArcturusZhang** [comment]
If we have explicit type tag on the values in the yaml, our deserializer of code model could properly handle the type, like:
```
                        enabledForDeployment:
                          schema: *ref_83
                          rawValue: !!bool true
                          language: *ref_550
```
I have locally tested this could work.
If the test modeler could output the yaml with these tags, it would be awesome - since as a value of a parameter in example, a literal value of `true` could either be a boolean or a string - only the test modeler know its exact type during generating it.
