### ISSUE TITLE
[CodeGenSuppress] and [CodeGenModel] not being applied to generated code

### ISSUE THREAD

**Issue by rquackenbush** [Azure/autorest.csharp#2714]
**Describe the bug**
I am attempting to customize two aspects of code generation for a c# client:
- The name of a model (`Person` to `PersonCustomized` via the `[CodeGenModel]` attribute
- Suppressing the generation of a method (`AddPersonAsync`) via the `[CodeGenSuppress]` attribute.

Open API file / command / options are included in the repro here: https://github.com/rquackenbush/AutoRestCustomizationRepro

**Expected behavior**
- The `Person` model should be generated as `PersonCustomized`
- The `AddPersonAsync` method should not be generated.

**Comment by AlexanderSher** [comment]
Paths for output folder and project folder were specified incorrectly:
``` yaml
input-file: swagger.json
csharp: true 
**output-folder: $(this-folder)/Generated**
namespace: AutoRestCustomizationRepro
skip-csproj: true
clear-output-folder: true
override-client-name: AutoRestCustomizationRepro
generation1-convenience-client: true
**project-folder: $(this-folder)**
```
