### ISSUE TITLE
TypeSpec generation1-convenience-client 

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest.csharp#3592]
We are using AutoRest C# to generate a couple `generation1-convenience-client`s.  We would like to move from OpenAPI to TypeSpec and use `tsp compile` to generate the client directly instead of exporting TypeSpec to OpenAPI. Right now, it is generating a DPG client that does not have public models. Can you please make it possible to generate a `generation1-convenience-client` directly from TypeSpec?

Current AutoRest configuration for one client:

``` yaml
title: ConsumptionWorker
model-namespace: false
public-clients: true
input-file:
- $(this-folder)/ConsumptionWorkerApi.yaml
generation1-convenience-client: true
```

Attempted `tspconfig.yaml`:
``` yaml
emit:
  - "@azure-tools/typespec-csharp"
options:
  "@azure-tools/typespec-csharp":
    # Output will be in a "Generated" folder under.
    emitter-output-dir: "{project-root}/../client"
    namespace: "ConsumptionWorkerApi"
    clear-output-folder: true
```

It would be great if there was a `generation1-convenience-client: true` option.

The MS internal PR to view the changes is [here](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS/pullrequest/8434440?_a=files). You can also reach me on Teams.
