### ISSUE TITLE
[DPG] Add flag to turn off sample generation for methods where the generation isn't good

### ISSUE THREAD

**Issue by joseharriaga** [Azure/autorest.csharp#3602]

**Comment by chunyu3** [comment]
define an operation-level flag to turn off sample generation for special operations.

**Comment by archerzz** [comment]
## Suggestion

Provide a property `suppress-examples` in `tspconfig.yml`. Its value is an array of which each element is `${ClientName}.${MethodName}`. 
- `ClientName` is the name of the generated client.
- `MethodName` is the name of the generated operation name. You don't need to append `Async`. Both sync and async versions will be suppressed.

It looks like:
```yaml
options:
  "@azure-tools/typespec-csharp":
    suppress-examples:
    - RestClient.CreateOrUpdate
```

@m-nash ^^
