### ISSUE TITLE
order or arguments changed for DPG client

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest.csharp#3644]
I'm switching over an internal API from Swagger to TypeSpec in this [internal PR](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS/pullrequest/8554320). The order of arguments in different before for this:

``` tsp
@route("/v1/region/{region}/pod/{podId}/skuName/{skuName}/specialPlacementConfigType/{configType}")
@put
op ChangeRegionalPodConfigTypeForSku(
  @doc("Pod id")
  @path
  @format("uuid")
  podId: string,

  @doc("region")
  @path
  region: string,

  @doc("SkuName")
  @path
  skuName: string,

  @doc("configType")
  @path
  configType: string,
): PodConfigType;
```

The C# using the new DPG is following the order defined in the `route`.
``` cs
        public virtual Response<PodConfigType> ChangeRegionalPodConfigTypeForSku(string region, Guid podId, string skuName, string configType, CancellationToken cancellationToken = default)
        {
```

Previously, it was following the order defined in the API spec:
``` cs
        public virtual async Task<Response> ChangeRegionalPodConfigTypeForSkuAsync(Guid podId, string region, string skuName, string configType, CancellationToken cancellationToken = default)
        {
```

Is this change by design?

**Comment by pshao25** [comment]
Could you provide the swagger you defined before? I cannot repro your previous observation.

**Comment by ArcturusZhang** [comment]
As far as I know, following the order as they defined in route is by design, we get that information from the typespec compiler directly. We never changed the order of parameters.

**Comment by cataggar** [comment]
@pshao25, the [swagger.yaml](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS/pullrequest/8554320?_a=files&path=/src/conveyor/conveyor/swagger.yaml) was in the linked PR as deleted. For that operation, it has
```
  "/v1/region/{region}/pod/{podId}/skuName/{skuName}/specialPlacementConfigType/{configType}":
    put:
      operationId: ChangeRegionalPodConfigTypeForSku
      parameters:
        - in: path
          name: podId
          description: Pod id
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: region
          description: region
          required: true
          schema:
            type: string
        - in: path
          name: skuName
          description: SkuName
          required: true
          schema:
            type: string
        - in: path
          name: configType
          description: configType
          required: true
          schema:
            type: string
      security:
        - OAuth2: []
      tags:
        - specialPlacementConfig
      summary: Change Status of Pod Exclusive or default
      responses:
        "202":
          description: successful operation
        "204":
          description: successful operation
```

**Comment by timotheeguerin** [comment]
Typ

> As far as I know, following the order as they defined in route is by design, we get that information from the typespec compiler directly. We never changed the order of parameters.

I don't think we do any sorting of the parameters. From typespec we would expect you to respect the way it was defined in the typespec and no in the root.

See this [playground example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHJvdXRlKCIve29uZX0ve3R3b8QGaHJlxA5mb3VyfSIpCm9wIHRlc3QoCiAgQHBhdGggdHdvOiBzdHJpbmcsyRXELtIWb25l0hXFYcoXKTogdm9pZDsK&e=%40typespec%2Fopenapi3&options=%7B%7D)  showing the parameters remains in the oder defined regardless of the `@route` 


```tsp
@route("/{one}/{two}/{three}/{four}")
op test(
  @path two: string,
  @path four: string,
  @path one: string,
  @path three: string,
): void;
```

produce
```yaml
parameters:
        - name: two
          in: path
          required: true
          schema:
            type: string
        - name: four
          in: path
          required: true
          schema:
            type: string
        - name: one
          in: path
          required: true
          schema:
            type: string
        - name: three
          in: path
          required: true
          schema:
            type: string
```
