### ISSUE TITLE
[MPG][.Net] wrong namespace and library-name in configuration.json for TSP MPG

### ISSUE THREAD

**Issue by live1206** [Azure/autorest.csharp#4090]
Configuration from emitter contains wrong content as below:
```json
{
  "namespace": "Microsoft.AzureSphere",
  "library-name": "Microsoft.AzureSphere",
}
```
They should be 
```json
{
  "namespace": "Azure.ResourceManager.Sphere",
  "library-name": "Sphere",
}
```

**Comment by live1206** [comment]
Resolved by adding options in tspconfig.yaml
```yml
  "@azure-tools/typespec-csharp":
    namespace: "Azure.ResourceManager.Sphere"
    library-name: "Sphere"
```
