### ISSUE TITLE
[MPG][.Net] Additional generated files with wrong namespace

### ISSUE THREAD

**Issue by live1206** [Azure/autorest.csharp#4099]
- The expected `ArmSphereModelFactory` generated with some methods missing, and an additional `ArmMicrosoftAzureSphereModelFactory` with wrong namespace `Microsoft.AzureSphere.Models`
- Under `LongRunningOperation`, additional `AzureSphereArmOperation` and `AzureSphereArmOperationOfT` with wrong namespace `Microsoft.AzureSphere`

**Comment by ArcturusZhang** [comment]
Do we have `namespace Microsoft.AzureSphere` in the typespec?
Sometimes our generator takes the `Namespace` of the typespec as library name when library is not configured in the configuration.

**Comment by live1206** [comment]
Resolved by adding options in tspconfig.yaml
```yml
  "@azure-tools/typespec-csharp":
    namespace: "Azure.ResourceManager.Sphere"
    library-name: "Sphere"
```
