### ISSUE TITLE
Examples being generated even if operation is suppressed

### ISSUE THREAD

**Issue by nisha-bhatia** [Azure/autorest.csharp#4120]
Examples are still generated after the operation that they use is suppressed. 

For example, in the following [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/0373f0edc4414fd402603fac51d0df93f1f70507/specification/monitor/resource-manager/Microsoft.Insights/stable/2023-10-01/metricDefinitions_API.json#L117): 
I suppress the Subscription operations by doing:
### Remove subscription scoped operations

``` yaml
directive:
  - remove-operation: MetricDefinitions_ListAtSubscriptionScope
  - remove-operation: Metrics_ListAtSubscriptionScope
  - remove-operation: Metrics_ListAtSubscriptionScopePost
```
But the examples using the MetricDefinitionsClient are still being generated:
![image](https://github.com/Azure/autorest.csharp/assets/67986960/638a4985-586c-43ab-85d3-696d0700804d)
If we don't have the client - we shouldn't be generating the samples. There is currently no way to not generate the examples using Autorest.
