### ISSUE TITLE
sample-gen flag does not respect output-folder

### ISSUE THREAD

**Issue by johnholliday** [Azure/autorest.csharp#4154]
Using the experimental 'sample-gen' flag to emit sample client code always generates the code into '../tests/Generated/Samples' no matter what output-folder is specified.

Sample code should be generated into the folder as specified, for example:

```yaml
csharp: true
sample-gen:
  output-folder: $(this-folder)/sample-code
```
