### ISSUE TITLE
tspconfig.yaml  "@azure-tools/typespec-csharp" flavor unsupported

### ISSUE THREAD

**Issue by quentinRobinson** [Azure/autorest.csharp#4498]
**Describe the issue or request**
When generating code from TSP with 

```yaml
options:
    "@azure-tools/typespec-csharp":
        package-dir: "Azure.AI.Language.AnalyzeText"
        clear-output-folder: true
        model-namespace: false
        namespace: "Azure.AI.Language.AnalyzeText"
        flavor: azure
```
generation fails with if I remove the flavor the generation works as intended.
```
  C:/src/azure-sdk-for-net/sdk/cognitivelanguage/Azure.AI.Language.AnalyzeText/TempTypeSpecFiles/Language.AnalyzeText/tspconfig.yaml:21:5 - error invalid-schema: Schema violation: must NOT have additional properties (/)
    additionalProperty: flavor
  > 21 |     flavor: azure
       |     ^^^^^^

  Found 1 error.
```
