### ISSUE TITLE
emitter-output-dir/Generated/src now instead of emitter-output-dir/Generated

### ISSUE THREAD

**Issue by cataggar** [Azure/autorest.csharp#4610]
I am upgrading from `"@azure-tools/typespec-csharp": "0.2.0-beta.20230723.1"` to `"@azure-tools/typespec-csharp": "0.2.0-beta.20240418.4"`.  It now generates to emitter-output-dir/Generated/src instead of emitter-output-dir/Generated. Why was `src` added? Is this change in behavior on purpose?

The `tspconfig.yaml` is this:
``` yaml
emit:
  - "@azure-tools/typespec-csharp"
options:
  "@azure-tools/typespec-csharp":
    # Output will be in a "Generated" folder under.
    emitter-output-dir: "{project-root}/../clients/dotnet"
    namespace: "ConveyorApi"
    clear-output-folder: true
    model-namespace: false
```
