### ISSUE TITLE
Type update based on naming for .NET SDK with TypeSpec input

### ISSUE THREAD

**Issue by live1206** [Azure/autorest.csharp#4792]
With swagger input, we have configuration in autorest.md as below for type mapping:
```yml
format-by-name-rules:
  'tenantId': 'uuid'
  'ETag': 'etag'
  'location': 'azure-location'
  'locationName': 'azure-location'
  'dataCenterLocation': 'azure-location'
  'hostId': 'uuid'
  '*Uri': 'Uri'
  '*Uris': 'Uri'
  'principalId': 'uuid'
  '*SubnetId': 'arm-id'
  'networkAclBypassResourceIds': 'arm-id'
  'partitionId': 'uuid'
  'instanceId': 'uuid'
```
With TypeSpec input, we need to find out a way to support this.
