### ISSUE TITLE
[P0] Get PreCheck/DuplicateSchema error when generating code for Resources RP

### ISSUE THREAD

**Issue by erich-wang** [Azure/autorest.csharp#758]
This is blocker issue for May preview.

When using autorest.md
``` yaml
azure-arm: true
input-file:
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-10-01/resources.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-11-01/subscriptions.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyAssignments.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyDefinitions.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policySetDefinitions.json
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Resources/preview/2019-10-01-preview/deploymentScripts.json
```
**We got error info:**

EXEC : error (PreCheck/DuplicateSchema): Duplicate Schema named Identity -- properties.principalId.description: undefined => "The principal ID of the resource identity.",properties.tenantId.description: undefined => "The tenant ID of the resource identity.",properties.type.description: undefined => "The identity type. This is the only required field when adding a system assigned identity to a resource.",properties.userAssignedIdentities: {"description":"The list of user identities associated with the resource. The user identity dictionary key references will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'.","$ref":"#/components/schemas/schemas:135"} => <none> ; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that. [C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src\Azure.Management.Resource.csproj]
FATAL : error : 1 errors occured -- cannot continue. [C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src\Azure.Management.Resource.csproj]
EXEC : error : Plugin prechecker reported failure. [C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src\Azure.Management.Resource.csproj]
C:\AME\work-azure-net-sdk\eng\CodeGeneration.targets(24,5): error MSB3073: The command "npx autorest@https://github.com/Azure/autorest/releases/download/autorest-3.0.6222/autorest-3.0.6222.tgz --version=3.0.6282 C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src/autorest.md  --use=https://github.com/Azure/autorest.csharp/releases/download/3.0.0-dev.20200512.16/autorest-csharp-v3-3.0.0-dev.20200512.16.tgz --output-folder=C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src --title=Azure.Management.Resource --namespace=Azure.Management.Resource --shared-source-folder=C:\AME\work-azure-net-sdk\eng\../sdk/core/Azure.Core/src/Shared/ --verbose" exited with code 1. [C:\AME\work-azure-net-sdk\sdk\resources\Azure.Management.Resource\src\Azure.Management.Resource.csproj]
