### ISSUE TITLE
Generate C# Enum

### ISSUE THREAD

**Issue by markm77** [Azure/autorest.csharp#863]
Hi there,

When generating model code from OpenAPI v3, I notice that enums like [this](https://github.com/OpenBankingUK/client-registration-api-specs/blob/v3.2/dist/client-registration-openapi.yaml#L196-L203) are converted to C# strings like this:

```csharp
        /// <summary>
        /// Gets or sets possible values include: 'private_key_jwt',
        /// 'client_secret_jwt', 'client_secret_basic', 'client_secret_post',
        /// 'tls_client_auth'
        /// </summary>
        [JsonProperty(PropertyName = "token_endpoint_auth_method")]
        public string TokenEndpointAuthMethod { get; set; }
```

Is there any way to convert to C# enums to allow better validation etc? Note that I cannot change the Open API YAML directly.

BR,
Mark

**Comment by markm77** [comment]
Okay worked out I can add ```x-ms-enum``` as shown below to get C# Enum but is there any way to automate adding ```x-ms-enum``` to all string enums? For example through ```transport``` in config file (which I already use to create operationIds)? I have lots of OpenAPI/Swagger files tagged in repo (e.g. see link in prev post) and really trying to avoid creating a separately maintained set.....

May thanks for any help!

```yaml
      token_endpoint_auth_method:
        type: string
        enum:
          - private_key_jwt
          - client_secret_jwt
          - client_secret_basic
          - client_secret_post
          - tls_client_auth
        x-ms-enum:
          name: token_endpoint_auth_method_enum
          modelAsString: false
```

**Comment by markm77** [comment]
I've been experimenting with things like below but doesn't work - any help appreciated!

```yaml
directive:
  - from: swagger-document # do it globally 
    where: $.definitions.*.enum
    set:
      x-ms-enum:
        modelAsString: false
```
