### ISSUE TITLE
swagger transform to a *next* operation generates AppendRaw(nextLink.. instead of AppendRawNextLink(nextLink...

### ISSUE THREAD

**Issue by christothes** [Azure/autorest.csharp#892]
Example transform:

```yaml
directive:
  - from: swagger-document
    where: $["x-ms-paths"]
    transform: >
      $["/{nextLink}?fooNext"] = {
        "post": {
          "tags": [
            "Foo"
          ],
          "summary": "foo",
          "operationId": "foo",
          "consumes": [
            "application/json"
          ],
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "in": "path",
              "name": "nextLink",
              "description": "the next link",
              "required": true,
              "type": "string",
              "x-ms-skip-url-encoding": true
            },
            {
              "in": "body",
              "name": "body",
              "description": "query options",
              "required": true,
              "schema": {
                "$ref": "#/definitions/FooQueryOption"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Success",
              "schema": {
                "$ref": "#/definitions/SomeModel"
              }
            },
            "default": {
              "description": "Client error or server error (4xx or 5xx)",
              "schema": {
                "$ref": "#/definitions/ErrorCode"
              }
            }
          },
          "x-ms-pageable": {
            "nextLinkName": null
          }
        }
      }
```

Generated code:
```C#
var uri = new RawRequestUriBuilder();
uri.AppendRaw(endpoint, false);
uri.AppendRaw("/foo/v1.0", false);
uri.AppendPath("/", false);
uri.AppendRaw(nextLink, false);
```

Expected:
```C#
var uri = new RawRequestUriBuilder();
uri.AppendRaw(endpoint, false);
uri.AppendRaw("/foo/v1.0", false);
uri.AppendRawNextLink(nextLink, false);
```
